In [1]:
pip install requests pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import requests
import pandas as pd

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
import requests

url = "https://api.open-meteo.com/v1/forecast?latitude=28.61&longitude=77.23&current_weather=true"

response = requests.get(url)

data = response.json()

print(data)

{'latitude': 28.625, 'longitude': 77.25, 'generationtime_ms': 0.4222393035888672, 'utc_offset_seconds': 0, 'timezone': 'GMT', 'timezone_abbreviation': 'GMT', 'elevation': 214.0, 'current_weather_units': {'time': 'iso8601', 'interval': 'seconds', 'temperature': '°C', 'windspeed': 'km/h', 'winddirection': '°', 'is_day': '', 'weathercode': 'wmo code'}, 'current_weather': {'time': '2026-03-08T13:00', 'interval': 900, 'temperature': 30.4, 'windspeed': 4.3, 'winddirection': 294, 'is_day': 0, 'weathercode': 0}}

In [3]:
import pandas as pd

temperature = data["current_weather"]["temperature"]
windspeed = data["current_weather"]["windspeed"]
winddirection = data["current_weather"]["winddirection"]

weather_record = {
    "city": "Delhi",
    "temperature": temperature,
    "windspeed": windspeed,
    "winddirection": winddirection
}

df = pd.DataFrame([weather_record])

df

    city  temperature  windspeed  winddirection
0  Delhi         30.4        4.3            294

In [4]:
import requests
import pandas as pd

cities = {
    "Delhi": (28.61, 77.23),
    "Mumbai": (19.07, 72.87),
    "London": (51.50, -0.12),
    "New York": (40.71, -74.00)
}

weather_data = []

for city, coords in cities.items():
    
    lat, lon = coords
    
    url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"
    
    response = requests.get(url)
    
    data = response.json()
    
    record = {
        "city": city,
        "temperature": data["current_weather"]["temperature"],
        "windspeed": data["current_weather"]["windspeed"],
        "winddirection": data["current_weather"]["winddirection"]
    }
    
    weather_data.append(record)

df = pd.DataFrame(weather_data)

df

       city  temperature  windspeed  winddirection
0     Delhi         29.7        4.2            290
1    Mumbai         28.5       16.0            337
2    London         10.6        8.3            114
3  New York         11.2        9.6            200

In [5]:
import requests
import pandas as pd
from datetime import datetime

cities = {
    "Delhi": (28.61, 77.23),
    "Mumbai": (19.07, 72.87),
    "London": (51.50, -0.12),
    "New York": (40.71, -74.00)
}

weather_data = []

for city, coords in cities.items():
    
    lat, lon = coords
    
    url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current_weather=true"
    
    response = requests.get(url)
    
    data = response.json()
    
    record = {
        "timestamp": datetime.now(),
        "city": city,
        "temperature": data["current_weather"]["temperature"],
        "windspeed": data["current_weather"]["windspeed"],
        "winddirection": data["current_weather"]["winddirection"]
    }
    
    weather_data.append(record)

df = pd.DataFrame(weather_data)

df

                   timestamp      city  temperature  windspeed  winddirection
0 2026-03-08 18:53:43.308506     Delhi         29.7        4.2            290
1 2026-03-08 18:53:44.270612    Mumbai         28.5       16.0            337
2 2026-03-08 18:53:45.242954    London         10.6        8.3            114
3 2026-03-08 18:53:46.349374  New York         11.2        9.6            200

In [6]:
df.to_csv("weather_data.csv", index=False)

In [7]:
df.to_csv("weather_data.csv", mode="a", header=False, index=False)